server:
  context-path: /zeus
  port: 10086
spring:
  datasource:
    url: jdbc:mysql://192.168.85.128:3306/zeus?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      stat-view-servlet:
        login-username: root
        login-password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
    