server:
  port: 10086
spring:
  redis:
    host: localhost
  http:
    encoding:
      charset: utf-8
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.0.141:3310/zeus?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      stat-view-servlet:
        login-username: root
        login-password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
     prefix: /WEB-INF/views/ # Read From Web Resources Dir
     suffix: .jsp
    favicon:
      enabled: true
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.com.zeus.common.model
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
swagger2: 
  api: 
    scanBasePackage: org.com.zeus.controller
